### ISSUE TITLE
Icons don't work in ie 10 and 11 when set as the background prop of an element that isn't square

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/fticons#40] opened 2017-07-07 17:43 UTC
The o-video play button is a rectangle, and in ie11/10 although the background property is set to `background-position: left` the icon is centred and crashes into some text.

A fix to this would be to as this thread( https://stackoverflow.com/questions/17944354/svg-background-image-position-is-always-centered-in-internet-explorer-despite-) suggests, to add 
`preserveAspectRatio="xMinYMid"`
However, this fix just changes the default position of the icon to always be left not center. It does not cause ie10/11 to respect the `background-position` property. So if you ever wanted to align it to the right, or center it would be wrong again. 

Here's a screen shot of this behaviour for every possible value for `preserveAspectRatio` against every possible value for `background-position`. In chrome, you can see, it respects `background-position` (the icons are the same across the rows)
In IE11/10 it respects the preserveAspectRatio value (the icons are the same by column)
![screen shot 2017-07-07 at 18 09 50](https://user-images.githubusercontent.com/68009/27969411-a09d2d9c-6342-11e7-9716-ca04307818ee.png)
![screen shot 2017-07-07 at 18 09 56](https://user-images.githubusercontent.com/68009/27969412-a3fe6596-6342-11e7-8bd8-fa98eb8e28ca.png)

I haven't been able to find a generic CSS hack or fix that makes ie11 respect the `background-position` for SVGs (this all works fine for PNGs). So I think this needs to be solved on a per-implementor basis.

1. Because o-video knows how big its button is going to be, it could do something like:

```css
_:-ms-fullscreen, :root .icon-svg {
  background-position: -120px;
}
```
Its possible that with this kind of solution we could add a parameter to oIconsGetIcon which asks for a negative margin value, but is does seem a bit redundant. Might as well leave it to implementors to work around this bug if they are using oIcons in this way.

2. Or it could add another element within the button which has the same aspect ratio as the icon (in this case they're all square) and set that div's background position and then position that div in the right place for the button.

3. Or an implementor could decide to use a PNG fallback for ie11/10 in their case. Again, they could construct their own background-image property hack for this, or we could add support for this in the mixin.

Anyway, at the very least, lets add something to a troubleshooting bit of the README as this is quite an annoying gotcha and @benbarnett and I have both spent a while trying to fix it at this point.

@benbarnett do you have any other suggestions for how we could fix this in oIcons?

**Comment by benbarnett** [comment] 2017-07-11 10:41
Thanks for the test case, this is super helpful.

As you say, the issue is probably best solved on a per-implementor basis; since the introduction of `placeholderHint` in o-video, the play button is both rectangle and of a variable width, depending on the text passed into the `placeholderHint` option. 

For o-video, I did [try another workaround](https://github.com/Financial-Times/o-video/pull/110), which is essentially option 2. I guess the question here is who is the implementor? o-video itself, or the section it's being used on?

On the homepage video section (where we first saw the issue), we are using a static button label (and therefore button width), so we can specify a pixel value background position. It does mean however that if the text were to change, we'd have to recalculate that position.

Could a fourth option be to pass a `$background-position: left|right|center|top|bottom` option to `oIconsGetIcon()`, which then adds the relevant `preserveAspectRatio` to the svg? I guess this could have a big impact on cache hits though...

For the immediate future, we can use the pixel position solution, but I shall keep pondering!

**Comment by JakeChampion** [comment] 2020-09-25 12:40
Since this has been open for so long, it seems we have inadvertently chosen option number 1 from Alice's suggestions:


> 1. Because o-video knows how big its button is going to be, it could do something like:
> 
> 
> ```css
> _:-ms-fullscreen, :root .icon-svg {
>   background-position: -120px;
> }
> ```
> 
> Its possible that with this kind of solution we could add a parameter to oIconsGetIcon which asks for a negative margin value, but is does seem a bit redundant. Might as well leave it to implementors to work around this bug if they are using oIcons in this way.

@Financial-Times/origami-core, shall we close this issue?

**Comment by JakeChampion** [comment] 2020-09-25 13:17
<img width="493" alt="image" src="https://user-images.githubusercontent.com/1569131/94271710-e6e1d500-ff39-11ea-8265-9d382379f0b3.png">

**Closed by JakeChampion** 2020-09-25 13:17 UTC
Labels: bug, imageset
